### ISSUE TITLE
Can't delete files in AVR

### ISSUE THREAD

**Issue by jenyoung** [nulib/avalon#450] opened 2019-09-17 20:16 UTC
### Severity

Is the production site running?
- [X] yes
- [ ] no

Are staff blocked from performing their work?
- [X] yes
- [ ] no

### Descriptive summary

I'm trying to delete some corrupted files from the Bienen collection that were ingested a while ago. I can't seem to be able to delete them. 

Example: https://media.northwestern.edu/media_objects/kw52j9098/section/cz30pt753

### Expected behavior

I can delete the file.

### Actual behavior

I cannot. 
The delete button acts like it works but it does not.

**Comment by davidschober** [comment] 2019-09-17 21:31
@jenyoung will unpublish all works in the collection that are bonked and add the query here. We will dig into this issue during a bi-fort-night.

**Comment by davidschober** [comment] 2019-10-14 16:48
@jenyoung now it looks like that item has been deleted. I can't remember what we ended up doing here.

**Comment by jenyoung** [comment] 2019-11-20 15:37
the 14 unpublished works in the `Northwestern University School of Music Concert Recordings` collection have files attached I need to delete and/or replace. @davidschober @mbklein

**Comment by davidschober** [comment] 2019-11-20 19:50
https://media.northwestern.edu/?f%5Bcollection_ssim%5D%5B%5D=Northwestern+University+School+of+Music+Concert+Recordings&f%5Bworkflow_published_sim%5D%5B%5D=Unpublished

Just to be clear, we should delete all of the works here?

**Comment by jenyoung** [comment] 2019-11-20 20:03
No, I can't delete any `files` in a work. Don't delete any of them.

**Comment by davidschober** [comment] 2019-11-20 21:10
cc: @mbklein I tried to remediate this as well. The files that got stuck can't be removed from the media object.

**Comment by mbklein** [comment] 2020-01-23 17:14
I've located the cause of this issue, but I don't understand why it's happening. Brendan and I are continuing to look into it.

**Comment by davidschober** [comment] 2020-01-23 21:38
Thanks! I tested this. On staging I'm getting a 504 on a delete operation. Eventually it seems to delete. Can we also up the idle timeout?

**Comment by davidschober** [comment] 2020-02-05 17:35
Fixed in staging, ready for Prod. Additionally we increased idle timeout which should help with some of the odd timeouts.

**Closed** 2020-02-17 15:54 UTC
Labels: Avalon, bug, production
