### ISSUE TITLE
Manage groups opens another tab

### ISSUE THREAD

**Issue by jenyoung** [nulib/avalon#390] opened 2018-06-20 19:19 UTC
When going to manage groups in AVR, clicking on the button for it opens another browser tab. 

Windows 10 PC, Chrome Version 66.0.3359.170 (Official Build) (64-bit)

**Comment by jenyoung** [comment] 2018-06-21 15:38
Also happening in production. testing in Firefox 60.0.1 (64-bit) on a Windows 10 PC.

**Comment by davidschober** [comment] 2018-06-25 16:06
Low priority as this was an existing bug. cc: @mbklein @carrickr

**Comment by mbklein** [comment] 2018-06-27 09:15
This is by design in core Avalon; changing it is an enhancement, not a bug.

**Comment by davidschober** [comment] 2018-08-16 19:58
Closing. We'll leave this as is for now.

**Closed by davidschober** 2018-08-16 19:58 UTC
Labels: bug, production, quality assurance, ready, staging
