### ISSUE TITLE
Embed doesn't work

### ISSUE THREAD

**Issue by egilchrist** [nulib/avalon#126] opened 2017-06-12 19:22 UTC
Tested embed and couldn't run it.  Tested in both Chrome and Firefox.  
![screen shot 2017-06-12 at 2 20 13 pm](https://user-images.githubusercontent.com/20909880/27051109-89ab9bfe-4f7a-11e7-8ae0-701a6564a3a0.png)
![screen shot 2017-06-12 at 2 23 54 pm](https://user-images.githubusercontent.com/20909880/27051194-d7adf5b8-4f7a-11e7-8d05-94f1d472135a.png)

**Comment by davidschober** [comment] 2017-06-13 18:52
Dupe of #127

**Closed by davidschober** 2017-06-13 18:52 UTC
Labels: bug
